#!/usr/bin/env bash
set -euo pipefail

# Имя выходного файла можно передать первым аргументом,
# по умолчанию будет guard_all.h
OUT=${1:-guard.h}

# Создаём/перезаписываем выходной заголовок и пишем шапку
cat > "$OUT" <<'EOF'
#ifndef GUARD_SINGLE_HEADER_HPP
#define GUARD_SINGLE_HEADER_HPP

// Single-file amalgamated header generated by make_one_header.sh
// Contains: macro.h, location.h, env.h, util.h, check.h, guard_main.h

EOF

# Порядок важен: сначала то, от чего зависят остальные
FILES=(
  "macro.h"
  "location.h"
  "env.h"
  "util.h"
  "check.h"
  "guard_main.h"
)

for f in "${FILES[@]}"; do
    echo "// ===== Begin $f =====" >> "$OUT"
    sed -E '
        /^#pragma once/d;
        /^#include\s+"[^"]+"/d;
    ' "$f" >> "$OUT"
    printf "\n// ===== End %s =====\n\n" "$f" >> "$OUT"
done

cat >> "$OUT" <<'EOF'
#endif // GUARD_SINGLE_HEADER_HPP
EOF
