param(
    [string]$Out = "guard.h"
)

# Шапка файла с include-guard'ом
$header = @"
// This file is auto-generated by make_one_header.ps1
// Contains: macro.h, location.h, env.h, util.h, check.h, guard_main.h

#ifndef GUARD_SINGLE_HEADER_HPP
#define GUARD_SINGLE_HEADER_HPP

"@

Set-Content -Path $Out -Value $header -Encoding utf8

# Порядок важен: сначала базовые штуки, потом зависящие от них
$files = @(
    "macro.h",
    "location.h",
    "env.h",
    "util.h",
    "check.h",
    "guard_main.h"
)

foreach ($f in $files) {
    Add-Content -Path $Out -Value ("// ===== Begin {0} =====" -f $f)

    Get-Content -Path $f | Where-Object {
        # Убираем #pragma once
        ($_ -notmatch '^\s*#pragma\s+once\b') -and
        # Убираем локальные include'ы вида #include "file.h"
        ($_ -notmatch '^\s*#include\s+"[^"]+"')
    } | Add-Content -Path $Out

    Add-Content -Path $Out -Value ""
    Add-Content -Path $Out -Value ("// ===== End {0} =====" -f $f)
    Add-Content -Path $Out -Value ""
}

$footer = @"
#endif // GUARD_SINGLE_HEADER_HPP
"@

Add-Content -Path $Out -Value $footer
